// 100+ Bible Verses about God's Strength, Protection, and Watchfulness over Israel

const bibleVerses = [
    "The LORD will keep you from all harm—he will watch over your life; the LORD will watch over your coming and going both now and forevermore. - Psalm 121:7-8",
    "For I will defend this city to save it, for my own sake and for the sake of my servant David. - Isaiah 37:35",
    "He who watches over Israel will neither slumber nor sleep. - Psalm 121:4",
    "I will bless those who bless you, and whoever curses you I will curse; and all peoples on earth will be blessed through you. - Genesis 12:3",
    "The LORD is your keeper; the LORD is your shade on your right hand. - Psalm 121:5",
    "For the eyes of the LORD range throughout the earth to strengthen those whose hearts are fully committed to him. - 2 Chronicles 16:9",
    "The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing. - Zephaniah 3:17",
    "But you, Israel, my servant, Jacob, whom I have chosen, you descendants of Abraham my friend, I took you from the ends of the earth, from its farthest corners I called you. I said, 'You are my servant'; I have chosen you and have not rejected you. - Isaiah 41:8-9",
    "The LORD will reign over them in Mount Zion from that day and forever. - Micah 4:7",
    "No weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the servants of the LORD. - Isaiah 54:17",
    "For the LORD has chosen Zion, he has desired it for his dwelling. - Psalm 132:13",
    "Pray for the peace of Jerusalem: May those who love you be secure. - Psalm 122:6",
    "See, I have engraved you on the palms of my hands; your walls are ever before me. - Isaiah 49:16",
    "The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing. - Zephaniah 3:17",
    "For you are a people holy to the LORD your God. The LORD your God has chosen you out of all the peoples on the face of the earth to be his people, his treasured possession. - Deuteronomy 7:6",
    "The eternal God is your refuge, and underneath are the everlasting arms. - Deuteronomy 33:27",
    "The LORD will fight for you; you need only to be still. - Exodus 14:14",
    "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand. - Isaiah 41:10",
    "But now, this is what the LORD says—he who created you, Jacob, he who formed you, Israel: Do not fear, for I have redeemed you; I have summoned you by name; you are mine. - Isaiah 43:1",
    "I will make you into a great nation, and I will bless you; I will make your name great, and you will be a blessing. - Genesis 12:2",
    "The LORD is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge, my shield and the horn of my salvation, my stronghold. - Psalm 18:2",
    "God is our refuge and strength, an ever-present help in trouble. - Psalm 46:1",
    "The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. - Isaiah 43:2",
    "The LORD Almighty is with us; the God of Jacob is our fortress. - Psalm 46:7",
    "This is what the LORD says: Restrain your voice from weeping and your eyes from tears, for your work will be rewarded. They will return from the land of the enemy. So there is hope for your descendants. - Jeremiah 31:16-17",
    "Comfort, comfort my people, says your God. Speak tenderly to Jerusalem, and proclaim to her that her hard service has been completed. - Isaiah 40:1-2",
    "For the LORD loves the just and will not forsake his faithful ones. Wrongdoers will be completely destroyed; the offspring of the wicked will perish. - Psalm 37:28",
    "The LORD will keep you from all evil; he will keep your life. - Psalm 121:7",
    "The angel of the LORD encamps around those who fear him, and he delivers them. - Psalm 34:7",
    "Even to your old age and gray hairs I am he, I am he who will sustain you. I have made you and I will carry you; I will sustain you and I will rescue you. - Isaiah 46:4",
    "The LORD will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame. - Isaiah 58:11",
    "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future. - Jeremiah 29:11",
    "But the Lord is faithful, and he will strengthen you and protect you from the evil one. - 2 Thessalonians 3:3",
    "The name of the LORD is a fortified tower; the righteous run to it and are safe. - Proverbs 18:10",
    "The LORD is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "My help comes from the LORD, the Maker of heaven and earth. - Psalm 121:2",
    "Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken. - Psalm 55:22",
    "The LORD himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged. - Deuteronomy 31:8",
    "You will not fear the terror of night, nor the arrow that flies by day, nor the pestilence that stalks in the darkness, nor the plague that destroys at midday. - Psalm 91:5-6",
    "A thousand may fall at your side, ten thousand at your right hand, but it will not come near you. - Psalm 91:7",
    "For he will command his angels concerning you to guard you in all your ways. - Psalm 91:11",
    "Because he loves me, says the LORD, I will rescue him; I will protect him, for he acknowledges my name. - Psalm 91:14",
    "The LORD is my shepherd, I lack nothing. He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul. - Psalm 23:1-3",
    "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me. - Psalm 23:4",
    "In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety. - Psalm 4:8",
    "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance. - Psalm 32:7",
    "The LORD watches over you—the LORD is your shade at your right hand. - Psalm 121:5",
    "For great is his love toward us, and the faithfulness of the LORD endures forever. Praise the LORD. - Psalm 117:2",
    "Nations will come to your light, and kings to the brightness of your dawn. Lift up your eyes and look about you: All assemble and come to you. - Isaiah 60:3-4",
    "The LORD is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "Trust in the LORD with all your heart and lean not on your own understanding. - Proverbs 3:5",
    "The LORD is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "Be strong and courageous. Do not be afraid or terrified because of them, for the LORD your God goes with you; he will never leave you nor forsake you. - Deuteronomy 31:6",
    "The LORD will establish you as his holy people, as he promised you on oath, if you keep the commands of the LORD your God and walk in obedience to him. - Deuteronomy 28:9",
    "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world. - John 16:33",
    "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you; the LORD turn his face toward you and give you peace. - Numbers 6:24-26",
    "The grass withers and the flowers fall, but the word of our God endures forever. - Isaiah 40:8",
    "Heaven and earth will pass away, but my words will never pass away. - Matthew 24:35",
    "Your word is a lamp for my feet, a light on my path. - Psalm 119:105",
    "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness. - 2 Timothy 3:16",
    "The word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart. - Hebrews 4:12",
    "Do not let this Book of the Law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful. - Joshua 1:8",
    "Blessed is the one who does not walk in step with the wicked or stand in the way that sinners take or sit in the company of mockers, but whose delight is in the law of the LORD, and who meditates on his law day and night. - Psalm 1:1-2",
    "I seek you with all my heart; do not let me stray from your commands. I have hidden your word in my heart that I might not sin against you. - Psalm 119:10-11",
    "The statutes of the LORD are trustworthy, making wise the simple. - Psalm 19:7",
    "Your statutes are my heritage forever; they are the joy of my heart. - Psalm 119:111",
    "How sweet are your words to my taste, sweeter than honey to my mouth! - Psalm 119:103",
    "The unfolding of your words gives light; it gives understanding to the simple. - Psalm 119:130",
    "Every word of God is flawless; he is a shield to those who take refuge in him. - Proverbs 30:5",
    "As the rain and the snow come down from heaven, and do not return to it without watering the earth and making it bud and flourish, so is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it. - Isaiah 55:10-11",
    "Man shall not live on bread alone, but on every word that comes from the mouth of God. - Matthew 4:4",
    "If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you. - John 15:7",
    "Sanctify them by the truth; your word is truth. - John 17:17",
    "Consequently, faith comes from hearing the message, and the message is heard through the word about Christ. - Romans 10:17",
    "Do not merely listen to the word, and so deceive yourselves. Do what it says. - James 1:22",
    "I have written these things to you who believe in the name of the Son of God so that you may know that you have eternal life. - 1 John 5:13",
    "The LORD reigns, let the earth be glad; let the distant shores rejoice. - Psalm 97:1",
    "Give thanks to the LORD, for he is good; his love endures forever. - Psalm 107:1",
    "Shout for joy to the LORD, all the earth. Worship the LORD with gladness; come before him with joyful songs. - Psalm 100:1-2",
    "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name. - Psalm 100:4",
    "Sing to the LORD a new song, for he has done marvelous things; his right hand and his holy arm have worked salvation for him. - Psalm 98:1",
    "Let everything that has breath praise the LORD. Praise the LORD. - Psalm 150:6",
    "Rejoice in the Lord always. I will say it again: Rejoice! - Philippians 4:4",
    "And we know that in all things God works for the good of those who love him, who have been called according to his purpose. - Romans 8:28",
    "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. - John 3:16",
    "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness. - 1 John 1:9",
    "Come to me, all you who are weary and burdened, and I will give you rest. - Matthew 11:28",
    "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid. - John 14:27",
    "Cast all your anxiety on him because he cares for you. - 1 Peter 5:7",
    "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. - Philippians 4:6",
    "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. - Philippians 4:7",
    "The LORD is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him. - Psalm 28:7",
    "The joy of the LORD is your strength. - Nehemiah 8:10",
    "Delight yourself in the LORD, and he will give you the desires of your heart. - Psalm 37:4",
    "Commit your way to the LORD; trust in him and he will do this. - Psalm 37:5",
    "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth. - Psalm 46:10",
    "Wait for the LORD; be strong and take heart and wait for the LORD. - Psalm 27:14",
    "Those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. - Isaiah 40:31",
    "I can do all this through him who gives me strength. - Philippians 4:13",
    "But he said to me, My grace is sufficient for you, for my power is made perfect in weakness. - 2 Corinthians 12:9",
    "The LORD is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    // Additional 150+ verses for full page coverage
    "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you. - Numbers 6:24-25",
    "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go. - Joshua 1:9",
    "The LORD is close to the brokenhearted and saves those who are crushed in spirit. - Psalm 34:18",
    "Trust in the LORD with all your heart and lean not on your own understanding. - Proverbs 3:5",
    "In all your ways submit to him, and he will make your paths straight. - Proverbs 3:6",
    "Commit to the LORD whatever you do, and he will establish your plans. - Proverbs 16:3",
    "Many are the plans in a person's heart, but it is the LORD's purpose that prevails. - Proverbs 19:21",
    "The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding. - Proverbs 9:10",
    "The righteous person may have many troubles, but the LORD delivers him from them all. - Psalm 34:19",
    "Cast all your anxiety on him because he cares for you. - 1 Peter 5:7",
    "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. - Philippians 4:6",
    "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. - Philippians 4:7",
    "Come to me, all you who are weary and burdened, and I will give you rest. - Matthew 11:28",
    "Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. - Matthew 11:29",
    "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid. - John 14:27",
    "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world. - John 16:33",
    "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. - John 3:16",
    "For God did not send his Son into the world to condemn the world, but to save the world through him. - John 3:17",
    "Whoever believes in the Son has eternal life, but whoever rejects the Son will not see life, for God's wrath remains on them. - John 3:36",
    "Jesus answered, I am the way and the truth and the life. No one comes to the Father except through me. - John 14:6",
    "I am the resurrection and the life. The one who believes in me will live, even though they die. - John 11:25",
    "I am the good shepherd. The good shepherd lays down his life for the sheep. - John 10:11",
    "My sheep listen to my voice; I know them, and they follow me. - John 10:27",
    "I give them eternal life, and they shall never perish; no one will snatch them out of my hand. - John 10:28",
    "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing. - John 15:5",
    "If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you. - John 15:7",
    "As the Father has loved me, so have I loved you. Now remain in my love. - John 15:9",
    "Greater love has no one than this: to lay down one's life for one's friends. - John 15:13",
    "You did not choose me, but I chose you and appointed you so that you might go and bear fruit. - John 15:16",
    "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! - 2 Corinthians 5:17",
    "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. - Ephesians 2:8",
    "Not by works, so that no one can boast. - Ephesians 2:9",
    "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do. - Ephesians 2:10",
    "And we know that in all things God works for the good of those who love him, who have been called according to his purpose. - Romans 8:28",
    "What, then, shall we say in response to these things? If God is for us, who can be against us? - Romans 8:31",
    "Who shall separate us from the love of Christ? Shall trouble or hardship or persecution or famine or nakedness or danger or sword? - Romans 8:35",
    "No, in all these things we are more than conquerors through him who loved us. - Romans 8:37",
    "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers. - Romans 8:38",
    "Neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord. - Romans 8:39",
    "The Spirit himself testifies with our spirit that we are God's children. - Romans 8:16",
    "Now if we are children, then we are heirs—heirs of God and co-heirs with Christ. - Romans 8:17",
    "I consider that our present sufferings are not worth comparing with the glory that will be revealed in us. - Romans 8:18",
    "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness. - Galatians 5:22",
    "Gentleness and self-control. Against such things there is no law. - Galatians 5:23",
    "So I say, walk by the Spirit, and you will not gratify the desires of the flesh. - Galatians 5:16",
    "Since we live by the Spirit, let us keep in step with the Spirit. - Galatians 5:25",
    "Do not be deceived: God cannot be mocked. A man reaps what he sows. - Galatians 6:7",
    "Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life. - Galatians 6:8",
    "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. - Galatians 6:9",
    "But seek first his kingdom and his righteousness, and all these things will be given to you as well. - Matthew 6:33",
    "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own. - Matthew 6:34",
    "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. - Matthew 7:7",
    "For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened. - Matthew 7:8",
    "If you, then, though you are evil, know how to give good gifts to your children, how much more will your Father in heaven give good gifts to those who ask him! - Matthew 7:11",
    "Enter through the narrow gate. For wide is the gate and broad is the road that leads to destruction, and many enter through it. - Matthew 7:13",
    "But small is the gate and narrow the road that leads to life, and only a few find it. - Matthew 7:14",
    "Not everyone who says to me, 'Lord, Lord,' will enter the kingdom of heaven, but only the one who does the will of my Father who is in heaven. - Matthew 7:21",
    "Therefore everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock. - Matthew 7:24",
    "The rain came down, the streams rose, and the winds blew and beat against that house; yet it did not fall, because it had its foundation on the rock. - Matthew 7:25",
    "All authority in heaven and on earth has been given to me. - Matthew 28:18",
    "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit. - Matthew 28:19",
    "And teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age. - Matthew 28:20",
    "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth. - Acts 1:8",
    "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved. - Acts 4:12",
    "Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord. - Acts 3:19",
    "The God of Abraham, Isaac and Jacob, the God of our fathers, has glorified his servant Jesus. - Acts 3:13",
    "You killed the author of life, but God raised him from the dead. We are witnesses of this. - Acts 3:15",
    "Everyone who calls on the name of the Lord will be saved. - Acts 2:21",
    "This Jesus is the stone you builders rejected, which has become the cornerstone. - Acts 4:11",
    "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us. - Ephesians 3:20",
    "To him be glory in the church and in Christ Jesus throughout all generations, for ever and ever! Amen. - Ephesians 3:21",
    "Be very careful, then, how you live—not as unwise but as wise, making the most of every opportunity, because the days are evil. - Ephesians 5:15-16",
    "Do not get drunk on wine, which leads to debauchery. Instead, be filled with the Spirit. - Ephesians 5:18",
    "Speaking to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord. - Ephesians 5:19",
    "Always giving thanks to God the Father for everything, in the name of our Lord Jesus Christ. - Ephesians 5:20",
    "Finally, be strong in the Lord and in his mighty power. - Ephesians 6:10",
    "Put on the full armor of God, so that you can take your stand against the devil's schemes. - Ephesians 6:11",
    "For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms. - Ephesians 6:12",
    "Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground. - Ephesians 6:13",
    "Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place. - Ephesians 6:14",
    "And with your feet fitted with the readiness that comes from the gospel of peace. - Ephesians 6:15",
    "In addition to all this, take up the shield of faith, with which you can extinguish all the flaming arrows of the evil one. - Ephesians 6:16",
    "Take the helmet of salvation and the sword of the Spirit, which is the word of God. - Ephesians 6:17",
    "And pray in the Spirit on all occasions with all kinds of prayers and requests. - Ephesians 6:18",
    "Rejoice in the Lord always. I will say it again: Rejoice! - Philippians 4:4",
    "Let your gentleness be evident to all. The Lord is near. - Philippians 4:5",
    "Do everything without grumbling or arguing. - Philippians 2:14",
    "So that you may become blameless and pure, children of God without fault in a warped and crooked generation. - Philippians 2:15",
    "Then you will shine among them like stars in the sky as you hold firmly to the word of life. - Philippians 2:15-16",
    "For to me, to live is Christ and to die is gain. - Philippians 1:21",
    "For it has been granted to you on behalf of Christ not only to believe in him, but also to suffer for him. - Philippians 1:29",
    "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves. - Philippians 2:3",
    "Not looking to your own interests but each of you to the interests of the others. - Philippians 2:4",
    "In your relationships with one another, have the same mindset as Christ Jesus. - Philippians 2:5",
    "Who, being in very nature God, did not consider equality with God something to be used to his own advantage. - Philippians 2:6",
    "Rather, he made himself nothing by taking the very nature of a servant, being made in human likeness. - Philippians 2:7",
    "And being found in appearance as a man, he humbled himself by becoming obedient to death—even death on a cross! - Philippians 2:8",
    "Therefore God exalted him to the highest place and gave him the name that is above every name. - Philippians 2:9",
    "That at the name of Jesus every knee should bow, in heaven and on earth and under the earth. - Philippians 2:10",
    "And every tongue acknowledge that Jesus Christ is Lord, to the glory of God the Father. - Philippians 2:11",
    "Set your minds on things above, not on earthly things. - Colossians 3:2",
    "For you died, and your life is now hidden with Christ in God. - Colossians 3:3",
    "When Christ, who is your life, appears, then you also will appear with him in glory. - Colossians 3:4",
    "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful. - Colossians 3:15",
    "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom. - Colossians 3:16",
    "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. - Colossians 3:17",
    "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters. - Colossians 3:23",
    "Since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving. - Colossians 3:24",
    "Devote yourselves to prayer, being watchful and thankful. - Colossians 4:2",
    "Be wise in the way you act toward outsiders; make the most of every opportunity. - Colossians 4:5",
    "Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone. - Colossians 4:6",
    "May God himself, the God of peace, sanctify you through and through. May your whole spirit, soul and body be kept blameless at the coming of our Lord Jesus Christ. - 1 Thessalonians 5:23",
    "The one who calls you is faithful, and he will do it. - 1 Thessalonians 5:24",
    "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus. - 1 Thessalonians 5:16-18",
    "Do not quench the Spirit. Do not treat prophecies with contempt but test them all; hold on to what is good. - 1 Thessalonians 5:19-21",
    "May the Lord make your love increase and overflow for each other and for everyone else, just as ours does for you. - 1 Thessalonians 3:12",
    "May he strengthen your hearts so that you will be blameless and holy in the presence of our God and Father. - 1 Thessalonians 3:13",
    "For God did not give us a spirit of timidity, but a spirit of power, of love and of self-discipline. - 2 Timothy 1:7",
    "So do not be ashamed of the testimony about our Lord or of me his prisoner. Rather, join with me in suffering for the gospel, by the power of God. - 2 Timothy 1:8",
    "He has saved us and called us to a holy life—not because of anything we have done but because of his own purpose and grace. - 2 Timothy 1:9",
    "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness. - 2 Timothy 3:16",
    "So that the servant of God may be thoroughly equipped for every good work. - 2 Timothy 3:17",
    "Preach the word; be prepared in season and out of season; correct, rebuke and encourage—with great patience and careful instruction. - 2 Timothy 4:2",
    "I have fought the good fight, I have finished the race, I have kept the faith. - 2 Timothy 4:7",
    "Now there is in store for me the crown of righteousness, which the Lord, the righteous Judge, will award to me on that day. - 2 Timothy 4:8",
    "The Lord will rescue me from every evil attack and will bring me safely to his heavenly kingdom. To him be glory for ever and ever. Amen. - 2 Timothy 4:18",
    "For the grace of God has appeared that offers salvation to all people. - Titus 2:11",
    "It teaches us to say No to ungodliness and worldly passions, and to live self-controlled, upright and godly lives in this present age. - Titus 2:12",
    "While we wait for the blessed hope—the appearing of the glory of our great God and Savior, Jesus Christ. - Titus 2:13",
    "Who gave himself for us to redeem us from all wickedness and to purify for himself a people that are his very own, eager to do what is good. - Titus 2:14",
    "He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit. - Titus 3:5",
    "Whom he poured out on us generously through Jesus Christ our Savior. - Titus 3:6",
    "So that, having been justified by his grace, we might become heirs having the hope of eternal life. - Titus 3:7",
    "Let us hold unswervingly to the hope we profess, for he who promised is faithful. - Hebrews 10:23",
    "And let us consider how we may spur one another on toward love and good deeds. - Hebrews 10:24",
    "Not giving up meeting together, as some are in the habit of doing, but encouraging one another—and all the more as you see the Day approaching. - Hebrews 10:25",
    "Now faith is confidence in what we hope for and assurance about what we do not see. - Hebrews 11:1",
    "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. - Hebrews 11:6",
    "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. - Hebrews 12:1",
    "And let us run with perseverance the race marked out for us, fixing our eyes on Jesus, the pioneer and perfecter of faith. - Hebrews 12:1-2",
    "For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God. - Hebrews 12:2",
    "Consider him who endured such opposition from sinners, so that you will not grow weary and lose heart. - Hebrews 12:3",
    "The Lord disciplines the one he loves, and he chastens everyone he accepts as his son. - Hebrews 12:6",
    "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace for those who have been trained by it. - Hebrews 12:11",
    "Jesus Christ is the same yesterday and today and forever. - Hebrews 13:8",
    "Keep your lives free from the love of money and be content with what you have, because God has said, Never will I leave you; never will I forsake you. - Hebrews 13:5",
    "So we say with confidence, The Lord is my helper; I will not be afraid. What can mere mortals do to me? - Hebrews 13:6",
    "Through Jesus, therefore, let us continually offer to God a sacrifice of praise—the fruit of lips that openly profess his name. - Hebrews 13:15",
    "And do not forget to do good and to share with others, for with such sacrifices God is pleased. - Hebrews 13:16"
];

// Initialize breaking news rotation
let currentVerseIndex = 0;

function rotateBibleVerses() {
    const breakingNewsText = document.getElementById('breakingNewsText');
    if (!breakingNewsText) return;

    // Fade out
    breakingNewsText.style.opacity = '0';
    
    setTimeout(() => {
        // Update text
        breakingNewsText.textContent = bibleVerses[currentVerseIndex];
        currentVerseIndex = (currentVerseIndex + 1) % bibleVerses.length;
        
        // Fade in
        breakingNewsText.style.opacity = '1';
    }, 500);
}

// Start rotation when page loads
document.addEventListener('DOMContentLoaded', () => {
    const breakingNewsText = document.getElementById('breakingNewsText');
    if (breakingNewsText) {
        breakingNewsText.style.transition = 'opacity 0.5s ease-in-out';
        
        // Set first verse immediately
        breakingNewsText.textContent = bibleVerses[0];
        currentVerseIndex = 1;
        
        // Rotate every 10 seconds
        setInterval(rotateBibleVerses, 10000);
    }
});
